packages:
  - ./
  - docs
  - playground
catalog:
  '@antfu/eslint-config': ^4.12.0
  '@nuxt/content': 3.5.1
  '@nuxt/devtools': ^2.4.0
  '@nuxt/eslint-config': ^1.3.0
  '@nuxt/fonts': 0.11.1
  '@nuxt/icon': 1.12.0
  '@nuxt/image': 1.10.0
  '@nuxt/kit': ^3.16.2
  '@nuxt/module-builder': ^1.0.1
  '@nuxt/schema': ^3.16.2
  '@nuxt/test-utils': ^3.17.2
  '@nuxt/ui': 3.1.0
  '@stripe/stripe-js': ^7.2.0
  '@types/node': ^22.14.1
  '@unocss/eslint-plugin': 66.1.0-beta.12
  changelogen: ^0.6.1
  eslint: ^9.25.1
  nuxt: ^3.16.2
  typescript: ^5.8.3
  vitest: ^3.1.2
  vue: ^3.5.13
  vue-router: ^4.5.0
  vue-tsc: ^2.2.10
catalogs:
  conflicts_nuxt_h3_14_159:
    nuxt: ^3.14.159
